from datetime import datetime, timezone

from .models import PaperContent


def build_report(
    paper: PaperContent,
    primitives: str,
    pain: str,
    pain_sources: str,
    crosspoll: str,
    infra: str,
    temporal: str,
    temporal_sources: str,
    redteam: str,
    redteam_sources: str,
    final: str,
) -> str:
    """Assemble all agent outputs into a single markdown report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    authors = ", ".join(paper.authors[:8])
    if len(paper.authors) > 8:
        authors += f" + {len(paper.authors) - 8} more"

    return f"""\
# 🚀 Product Ideas from: {paper.title}

> **arXiv**: [{paper.arxiv_id}](https://arxiv.org/abs/{paper.arxiv_id})
> **Authors**: {authors}
> **Generated**: {now}

---

## Table of Contents

1. [Executive Summary — Ranked Product Ideas](#executive-summary--ranked-product-ideas)
2. [Technical Primitives](#technical-primitives)
3. [Market Pain Mapping](#market-pain-mapping)
4. [Cross-Pollinated Ideas](#cross-pollinated-ideas)
5. [Infrastructure Inversion](#infrastructure-inversion--second-order-opportunities)
6. [Temporal Arbitrage](#temporal-arbitrage)
7. [Red Team Destruction](#red-team-destruction)

---

## Abstract (source paper)

{paper.abstract}

---

## Executive Summary — Ranked Product Ideas

{final}

---

## Technical Primitives

> Atomic building blocks extracted from the paper, independent of the authors' framing.

{primitives}

---

## Market Pain Mapping

> Real-world pain points discovered via web research, mapped to the primitives above.

{pain}

{pain_sources}

---

## Cross-Pollinated Ideas

> Non-obvious combinations of primitives × pain points across industries.

{crosspoll}

---

## Infrastructure Inversion — Second-Order Opportunities

> What NEW problems does widespread adoption of this technique create?

{infra}

---

## Temporal Arbitrage

> Products viable NOW that won't be obvious for 12-24 months.

{temporal}

{temporal_sources}

---

## Red Team Destruction

> Every idea attacked from 5 angles. Only survivors make it to the executive summary.

{redteam}

{redteam_sources}

---

*Generated by arxiv2product — multi-agent adversarial pipeline using [Agentica](https://agentica.symbolica.ai)*
"""
