from __future__ import annotations

import asyncio
import os
from pathlib import Path

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field
from dotenv import load_dotenv

from .feedback import score_feedback
from .service_store import ServiceStore

PACKAGE_ROOT = Path(__file__).resolve().parents[2]
WORKSPACE_ROOT = PACKAGE_ROOT.parent

load_dotenv(PACKAGE_ROOT / ".env")
load_dotenv(WORKSPACE_ROOT / ".env")

SERVICE_DB_PATH = Path(os.getenv("ARXIV2PRODUCT_SERVICE_DB", "data/service.db"))
store = ServiceStore(SERVICE_DB_PATH)
app = FastAPI(title="arxiv2product service", version="0.1.0")


class CreateReportRequest(BaseModel):
    paperRef: str = Field(min_length=3)
    userId: str = Field(min_length=1)
    model: str | None = None


class FeedbackRequest(BaseModel):
    reportId: str = Field(min_length=1)
    userId: str = Field(min_length=1)
    honestyRating: int = Field(ge=1, le=5)
    usefulnessRating: int = Field(ge=1, le=5)
    detailedFeedback: str = Field(min_length=20)


def _summarize_markdown(markdown: str) -> str:
    lines = [line.strip() for line in markdown.splitlines() if line.strip()]
    for line in lines:
        if line.startswith("> "):
            return line[2:][:240]
    return (lines[0] if lines else "Scientific paper report generated by arxiv2product.")[:240]


def _extract_report_title(markdown: str, fallback: str) -> str:
    for line in markdown.splitlines():
        if line.startswith("# 🚀 Product Ideas from: "):
            return line.removeprefix("# 🚀 Product Ideas from: ").strip()
        if line.startswith("# "):
            return line.removeprefix("# ").strip()
    return fallback


async def _run_report_job(job_id: str, paper_ref: str, model: str | None) -> None:
    from .pipeline import DEFAULT_MODEL, run_pipeline

    store.mark_job_running(job_id)
    try:
        output_path = await run_pipeline(paper_ref, model=model or DEFAULT_MODEL)
        markdown = Path(output_path).read_text(encoding="utf-8")
        store.complete_report_job(
            job_id=job_id,
            title=_extract_report_title(markdown, paper_ref),
            paper_id=paper_ref,
            summary=_summarize_markdown(markdown),
            markdown=markdown,
        )
    except Exception as exc:
        store.fail_report_job(job_id, str(exc))


@app.get("/health")
async def health() -> dict[str, str]:
    return {"status": "ok"}


@app.get("/dashboard/{user_id}")
async def dashboard(user_id: str) -> dict[str, object]:
    return store.get_dashboard_snapshot(user_id)


@app.post("/reports")
async def create_report(request: CreateReportRequest) -> dict[str, object]:
    try:
        job = store.create_report_job(
            user_id=request.userId,
            paper_ref=request.paperRef,
            model=request.model,
        )
    except ValueError as exc:
        raise HTTPException(status_code=402, detail=str(exc)) from exc

    asyncio.create_task(_run_report_job(job["id"], request.paperRef, request.model))
    return job


@app.get("/reports/{job_id}")
async def get_report(job_id: str) -> dict[str, object]:
    report = store.get_report_job(job_id)
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")
    return report


@app.post("/feedback/score")
async def score_feedback_endpoint(request: FeedbackRequest) -> dict[str, object]:
    report = store.get_report_job(request.reportId)
    if report is None:
        raise HTTPException(status_code=404, detail="Report not found")

    score = await score_feedback(
        report_title=str(report["title"]),
        report_summary=str(report["summary"]),
        honesty_rating=request.honestyRating,
        usefulness_rating=request.usefulnessRating,
        detailed_feedback=request.detailedFeedback,
    )
    return store.record_feedback(
        user_id=request.userId,
        report_job_id=request.reportId,
        honesty_rating=request.honestyRating,
        usefulness_rating=request.usefulnessRating,
        detailed_feedback=request.detailedFeedback,
        score=score.as_dict(),
    )


def run() -> None:
    import uvicorn

    uvicorn.run("arxiv2product.service:app", host="127.0.0.1", port=8010, reload=False)
